// FETCHING
export const FETCHING = 'FETCHING';

// USER
export const USER_DATA_RECEIVED = 'USER_DATA_RECEIVED';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';
export const LOAD_AVATAR_BY_URL = 'LOAD_AVATAR_BY_URL';

// UI
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const ADD_MASONRY = 'ADD_MASONRIES';
export const MOUNT_MASONRIES = 'CLEAR_MASONRIES';
export const REFRESH_MASONRIES_ARRAY = 'REFRESH_MASONRIES_ARRAY';
export const TOGGLE_CREATE_CARD = 'TOGGLE_CREATE_CARD';
export const CLOSE_CREATE_CARD = 'CLOSE_CREATE_CARD';

// CARD
export const CREATE_CARD = 'CREATE_CARD';
export const TOGGLE_CARD = 'TOGGLE_CARD';
export const TO_ARCHIVE_CARD = 'TO_ARCHIVE_CARD';
export const TO_HOME_CARD = 'TO_HOME_CARD';
export const TO_TRASH_CARD = 'TO_TRASH_CARD';
export const DELETE_FOREVER_CARD = 'DELETE_FOREVER_CARD';
export const MAKE_COPY_OF_CARD = 'MAKE_COPY_OF_CARD';
export const CHANGE_BG_COLOR = 'CHANGE_BG_COLOR';
export const OPEN_EDITING_CARD = 'OPEN_EDITING_CARD';
export const CLOSE_EDITING_CARD = 'CLOSE_EDITING_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';

// FILTER
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';